CREATE PROCEDURE DROP_TABLE_IF_EXISTS(IN TABLE_NAME VARCHAR(64))
PARAMETER STYLE JAVA MODIFIES SQL DATA LANGUAGE JAVA EXTERNAL NAME
  'net.ripe.rpki.validator.StoredProcedures.dropTableIfExists';

CALL DROP_TABLE_IF_EXISTS('LATEST_HTTP_SNAPSHOT');

DROP PROCEDURE DROP_TABLE_IF_EXISTS;