BEGIN;

ALTER TABLE certificates   ADD COLUMN ta_name CHARACTER VARYING(80);
ALTER TABLE repo_objects   ADD COLUMN ta_name CHARACTER VARYING(80);
ALTER TABLE broken_objects ADD COLUMN ta_name CHARACTER VARYING(80);

COMMIT;
